apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: authsecret
spec:
  provider: vault
  parameters:
    vaultAddress: http://<vaultfqdn>:8200
    roleName: database
    objects: |
      - objectName: "group-security-configurations.xml"
        secretPath: "<secretspath>/data/authsecret"
        secretKey: "group-security-configurations.xml"
      - objectName: "webSecurity.xml"
        secretPath: "<secretspath>/data/authsecret"
        secretKey: "webSecurity.xml"
