# Accept the terms of the IBM license by setting the license parameter to "true"
license: true

image:
  repository: cp.icr.io/cp/cp4a/odm
## Optionally specify an list of imagePullSecrets.
## Secrets must be manually created in the namespace.
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  pullSecrets:
  - ibm-entitlement-key

internalDatabase:
  persistence:
    enabled: false
  runAsUser: ""
  secretCredentials:
    name: odmdbsecret
    type: spc

service:
  enableRoute: true

customization:
  authSecretRef:
    name: authsecret
    type: spc
  runAsUser: ''
  securitySecretRef:
    name: mynicecompanytlssecret
    type: spc

serviceAccountName: odm-sa
