license: true
usersPassword: "odmAdmin"

image:
  pullSecrets:
  - <REGISTRY_SECRET>

service:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/backend-protocol: "HTTPS"
      alb.ingress.kubernetes.io/certificate-arn: "arn:aws:iam::<AWS-AccountId>:server-certificate/mycompany"

externalDatabase:
  type: postgres
  secretCredentials: odm-db-secret
  port: 5432
  serverName: <RDS_DB_ENDPOINT>
  databaseName: <RDS_DATABASE_NAME>
