license: true
usersPassword: "odmAdmin"

image:
  repository: cp.icr.io/cp/cp4a/odm
  pullSecrets:
  - my-odm-docker-registry

service:
  ingress:
    enabled: true
    class: nginx
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: https

externalDatabase:
  type: postgres
  secretCredentials: odm-db-secret
  port: 5432
  serverName: <RDS_DB_ENDPOINT>
  databaseName: <RDS_DATABASE_NAME>
