---
# GatewayClass - Defines the controller that will manage UMS Gateway
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: ums-alb-gateway-class
spec:
  controllerName: gateway.k8s.aws/alb
---
# LoadBalancerConfiguration - AWS-specific configuration for the UMS ALB
apiVersion: gateway.k8s.aws/v1
kind: LoadBalancerConfiguration
metadata:
  name: ums-alb-config
spec:
  scheme: internet-facing
  listenerConfigurations:
    - protocolPort: HTTPS:443
      #Provide the ARN of the certificate created in ACM/IAM
      defaultCertificate: arn:aws:iam::<AWS-AccountId>:server-certificate/mycompany
---
# TargetGroupConfiguration for IBM Usage Metering Service (ibm-usage-metering-fetch)
apiVersion: gateway.k8s.aws/v1
kind: TargetGroupConfiguration
metadata:
  name: ibm-usage-metering-tgc
spec:
  targetReference:
    kind: Service
    name: ibm-usage-metering-instance
  defaultConfiguration:
    # Using IP target type to support ClusterIP service
    targetType: ip
    protocol: HTTPS
    protocolVersion: HTTP1
    healthCheckConfig:
      healthCheckProtocol: HTTPS
      healthCheckPath: /ready
      healthCheckInterval: 30
      healthCheckTimeout: 5
      healthyThresholdCount: 2
      unhealthyThresholdCount: 2
---
# TargetGroupConfiguration for IBM Licensing Service (ls-port)
apiVersion: gateway.k8s.aws/v1
kind: TargetGroupConfiguration
metadata:
  name: ibm-licensing-tgc
spec:
  targetReference:
    kind: Service
    name: ibm-usage-metering-instance
  defaultConfiguration:
    # Using IP target type to support ClusterIP service
    targetType: ip
    protocol: HTTPS
    protocolVersion: HTTP1
    healthCheckConfig:
      healthCheckProtocol: HTTPS
      healthCheckPath: /
      healthCheckInterval: 30
      healthCheckTimeout: 5
      healthyThresholdCount: 2
      unhealthyThresholdCount: 2
---
# Gateway - Creates a dedicated AWS Application Load Balancer for UMS
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: ums-gateway
spec:
  gatewayClassName: ums-alb-gateway-class
  infrastructure:
    parametersRef:
      kind: LoadBalancerConfiguration
      name: ums-alb-config
      group: gateway.k8s.aws
  listeners:
  - name: https
    protocol: HTTPS
    port: 443
    allowedRoutes:
      namespaces:
        from: Same
---
# HTTPRoute for IBM Usage Metering Service and IBM Licensing Service
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: usage-metering-route
spec:
  parentRefs:
  - name: ums-gateway
    sectionName: https
  rules:
  # IBM Licensing Service
  - matches:
    - path:
        type: PathPrefix
        value: /ibm-licensing
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /
    backendRefs:
    - name: ibm-usage-metering-instance
      port: 8082
  # IBM Usage Metering Service
  - matches:
    - path:
        type: PathPrefix
        value: /ibm-usage-metering-instance
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /
    backendRefs:
    - name: ibm-usage-metering-instance
      port: 8080
