apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- all.yaml
patches:
- target:
    kind: Deployment
    name: .*-odm-decisionserverconsole
  patch: |-
    - op: replace
      path: /spec/template/spec/automountServiceAccountToken
      value: true
    - op: add
      path: /spec/replicas
      value: 2
- target:
    kind: Service
    name: .*-odm-decisionserverconsole
  patch: |-
    - op: add
      path: /spec/selector/status
      value: active
- target:
    kind: Service
    name: .*-odm-decisionserverconsole-notif
  patch: |-
    - op: add
      path: /spec/selector/status
      value: active
