license: true
usersPassword: odmAdmin

image:
  repository: cp.icr.io/cp/cp4a/odm
  pullSecrets:
  - ibm-entitlement-key

customization:
  runAsUser: ""

serviceAccountName: "custom-service-account" # make sure this is the name of the custom service account

decisionServerConsole:
  sidecar:
    enabled: true
    confSecretRef: res-console-sidecar
    probes:
      livenessProbe:
        exec:
          command:
          - /tmp/sidecarconf/sidecar-liveness-probe.sh
        initialDelaySeconds: 30
        periodSeconds: 30
        timeoutSeconds: 5
        successThreshold: 1
        failureThreshold: 3

internalDatabase:
  runAsUser: ""
  populateSampleData: true
  persistence:
    enabled: false

service:
  enableRoute: true