 mode: "deployment"
 config:
   exporters:
     otlp:
       endpoint: jaeger-all-in-one-inmemory-collector.tracing-system.svc.cluster.local:4317
       tls:
         insecure: true
   extensions:
     health_check:
       endpoint: ${env:MY_POD_IP}:13133
   receivers:
     jaeger:
       protocols:
         grpc:
           endpoint: ${env:MY_POD_IP}:14250
         thrift_http:
           endpoint: ${env:MY_POD_IP}:14268
         thrift_compact:
           endpoint: ${env:MY_POD_IP}:6831
     otlp:
       protocols:
         grpc:
           endpoint: ${env:MY_POD_IP}:4317
         http:
           endpoint: ${env:MY_POD_IP}:4318
   service:
     pipelines:
       traces:
         exporters:
           - otlp
         processors:
           - batch
         receivers:
           - otlp
           - jaeger
