 kind: OpenTelemetryCollector
metadata:
  name: otel-collector
  namespace: otel-demo
spec:
  mode: "deployment"
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: ${env:MY_POD_IP}:4317
          http:
            endpoint: ${env:MY_POD_IP}:4318
    service:
      pipelines:
        traces:
          exporters:
            - otlp
          processors:
            - batch
          receivers:
            - otlp
