kind: ConfigMap
apiVersion: v1
metadata:
  name: otel-collector-conf
  labels:
    app: opentelemetry
    component: otel-collector-conf
data:
  otel-collector-config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
    processors:
    extensions:
      health_check: {}
    exporters:
      otlp/jaeger:
        endpoint: "jaeger-all-in-one-inmemory-collector.tracing-system.svc.cluster.local:4317"
        insecure: true
      logging:

    service:
      extensions: [health_check]
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [otlp/jaeger]
---
kind: Service
apiVersion: v1
metadata:
  name: otel-collector
  labels:
    app: opentelemetry
    component: otel-collector
spec:
  ports:
    - name: otlp
      protocol: TCP
      port: 4317
      targetPort: 4317
    - name: metrics
      protocol: TCP
      port: 9092
      targetPort: 9092
  type: NodePort
  selector:
    component: otel-collector
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: otel-collector
  labels:
    app: opentelemetry
    component: otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opentelemetry
      component: otel-collector
  template:
    metadata:
      labels:
        app: opentelemetry
        component: otel-collector
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: '9092'
        prometheus.io/scrape: 'true'
    spec:
      volumes:
        - name: otel-collector-config-vol
          configMap:
            name: otel-collector-conf
            items:
              - key: otel-collector-config
                path: otel-collector-config.yaml
            defaultMode: 420
      containers:
        - resources:
            limits:
              cpu: '1'
              memory: 2Gi
            requests:
              cpu: 200m
              memory: 400Mi
          readinessProbe:
            httpGet:
              path: /
              port: 13133
              scheme: HTTP
          name: otel-collector
          command:
            - /otelcol
            - '--config=/conf/otel-collector-config.yaml'
            - '--mem-ballast-size-mib=683'
          livenessProbe:
            httpGet:
              path: /
              port: 13133
              scheme: HTTP
          env:
            - name: GOGC
              value: '80'
          ports:
            - containerPort: 4317
              protocol: TCP
            - containerPort: 8889
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: otel-collector-config-vol
              mountPath: /conf
          image: 'otel/opentelemetry-collector:0.6.0'
