apiVersion: v1
kind: Secret
metadata:
  name: tempo-storage
  namespace: otel-demo
stringData:
  endpoint: http://minio.otel-demo.svc:9000
  bucket: tempo
  access_key_id: tempo
  access_key_secret: supersecret
type: Opaque
