license: true
usersPassword: <password>

image:
  repository: cp.icr.io/cp/cp4a/odm
  pullSecrets:
  - <registrysecret>

service:
  type: LoadBalancer

externalDatabase:
  type: postgres
  secretCredentials: <odmdbsecret>
  port: 5432
  serverName: <postgresqlserver>.postgres.database.azure.com
  databaseName: postgres

customization:
  securitySecretRef: <mynicecompanytlssecret>
