oidc:
  enabled: true
customization:
  runAsUser: ''
  authSecretRef: azuread-auth-secret
  trustedCertificateList:
  - ms-secret
  - digicert-secret
  privateCertificateList:
  - myodmcompany
image:
  repository: cp.icr.io/cp/cp4a/odm
  pullSecret: icregistry-secret
internalDatabase:
  persistence:
    enabled: false
#  populateSampleData: true
  runAsUser: ''
license: true
service:
  enableRoute: true
