# Accept the terms of the IBM license by setting the license parameter to "true"
license: true

# Users password is required if authSecretRef is not set.
# Set the password for odm default users.
usersPassword: "odmAdmin"

image:
  repository: cp.stg.icr.io/cp/cp4a/odm/
  tag: 9.0.0.0
## Optionally specify an list of imagePullSecrets.
## Secrets must be manually created in the namespace.
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  pullSecrets:
  - ibm-registry

service:
  enableRoute: true

externalDatabase:
  type: "postgresql"
  serverName: "myexternalpostgres-ibm-postgres-dev.odm-privileged.svc.cluster.local"
  databaseName: "postgresdb"
  secretCredentials: "odm-prod-secret"
  port: "5432"

customization:
  runAsUser: ''

vault:
  enabled: true
  type: spc

serviceAccountName: "odm-sa"
