version: "3.8"

# To create a namespace in CloudMap required by Service Connect
x-cloudmap:
  PrivateNamespace:
    Name: odm-namespace

# To declare that the network for the ODM applications is via PublicSubnets
networks:
  application:
    x-vpc: PublicSubnets

# To lookup and use an existing VPC in AWS 
x-vpc:
  Lookup:
    VpcId:
      Tags:
        - Name: <aws_existing_vpc>
    AppSubnets: {}
    PublicSubnets:
      Tags:
        - <tag_label>: <tag_label_value>
    PrivateSubnets: {}
    StorageSubnets: {}

# To lookup an exising internet-facing Loadbalancer and setup Listener rules on it 
x-elbv2:
  public-alb:
    Lookup:
      loadbalancer:
        Tags:
          <loadbalance_tag>: <loadbalancer_tag_value>
    MacroParameters:
      Ingress:
        ExtSources:
          - IPv4: "0.0.0.0/0"
            Description: ANY
    Properties:
      Scheme: internet-facing
      Type: application
    Listeners:
    # Declare to use port 80 and the access paths for each ODM components
    # If the port is used, change it to another value. 
      - Port: 80 
        Protocol: HTTP
        Targets:
          - name: odm:odm-decisionserverconsole
            access: /res
          - name: odm:odm-decisionserverconsole
            access: /res/*            
          - name: odm:odm-decisioncenter
            access: /decisioncenter
          - name: odm:odm-decisioncenter
            access: /decisioncenter/*
          - name: odm:odm-decisioncenter
            access: /decisioncenter-api/*
          - name: odm:odm-decisionrunner
            access: /DecisionRunner
          - name: odm:odm-decisionrunner
            access: /DecisionRunner/*
          - name: odm:odm-decisionserverruntime
            access: /DecisionService
          - name: odm:odm-decisionserverruntime
            access: /DecisionService/*
    # Target services
    Services:
      odm:odm-decisionserverconsole:
        port: 9080
        protocol: HTTP
        healthcheck: 9080:HTTP:/res/login.jsf:200
      odm:odm-decisioncenter:
        port: 9060
        protocol: HTTP
        healthcheck: 9060:HTTP:/decisioncenter/healthCheck:200
      odm:odm-decisionrunner:
        port: 9081
        protocol: HTTP
        healthcheck: 9081:HTTP:/DecisionRunner:302
      odm:odm-decisionserverruntime:
        port: 9082
        protocol: HTTP
        healthcheck: 9082:HTTP:/DecisionService:302
        
services:
  odm-decisionserverconsole:
    image: cp.icr.io/cp/cp4a/odm/odm-decisionserverconsole:8.12.0.1-amd64
    x-aws-pull_credentials:  "arn:aws:secretsmanager:<aws_deployment_region>:<aws_account_id>:secret:IBMCPSecret-XXXXXX"
    # Optional: Set to true, to enable execute command and access the container
    x-ecs:
      EnableExecuteCommand: true
    # To enable Service Connect with "Client and server" option
    x-network:
      AssignPublicIp: true
      x-ecs_connect:
        MacroParameters:
          service_ports:
            tcp_1883:
              DnsName: odm-decisionserverconsole
              CloudMapServiceName: odm-decisionserverconsole-service
          x-cloudmap: PrivateNamespace
    restart: always
    networks:
      - application
    ports:
      - 9080
      - 1883/tcp
    environment:
      - USERS_PASSWORD=odmAdmin
      - HTTP_PORT=9080
      - DB_TYPE=postgres
      - DB_USER=<db_user>
      - DB_PASSWORD=<db_pwd>
      - DB_NAME=odmdb
      # Amazon RDS instance created for ODM. An example of the endpoint: odm-rds.XXXXXXX.eu-central-1.rds.amazonaws.com
      - DB_SERVER_NAME=<amazon_rds_endpoint>
    labels:
      - productName=IBM Operational Decision Manager
      - productID=e32af5770e06427faae142993c691048
      - productVersion=8.12.0.1
      - productMetric=FREE
      - productChargedContainers=decisionserverconsole
    logging:
      driver: "awslogs"
    x-aws-policies:
      - arn:aws:iam::<aws_account_id>:policy/<policy_allow_access_S3_bucket>
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 512M
      labels:
        ecs.task.family: odm
    expose:
      - 1883/tcp
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "http://localhost:9080/res/login.jsf"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 50s

  odm-decisioncenter:
    image: cp.icr.io/cp/cp4a/odm/odm-decisioncenter:8.12.0.1-amd64
    x-aws-pull_credentials: "arn:aws:secretsmanager:<aws_deployment_region>:<aws_account_id>:secret:IBMCPSecret-XXXXXX"  
    x-ecs:
      EnableExecuteCommand: true
    restart: always
    networks:
      - application
    environment:
      - DECISIONSERVERCONSOLE_PORT=9080
      - DECISIONRUNNER_PORT=9081
      - HTTP_PORT=9060
      - DECISION_MODEL_DISABLED=true
      - DB_TYPE=postgres
      - DB_USER=<db_user>
      - DB_PASSWORD=<db_pwd>
      - DB_NAME=odmdb
      # Amazon RDS instance created for ODM. An example of the endpoint: odm-rds.XXXXXXX.eu-central-1.rds.amazonaws.com
      - DB_SERVER_NAME=<amazon_rds_endpoint>
    logging:
      driver: "awslogs"
    x-aws-policies:
      - arn:aws:iam::<aws_account_id>:policy/<policy_allow_access_S3_bucket>
    ports:
      - 9060
    labels:
      - productName=IBM Operational Decision Manager
      - productID=b1a07d4dc0364452aa6206bb6584061d
      - productVersion=8.12.0.1
      - productMetric=PROCESSOR_VALUE_UNIT
      - productChargedContainers=decisioncenter
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 1G
      labels:
        ecs.task.family: odm
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "http://localhost:9060/decisioncenter/healthCheck"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 50s

  odm-decisionrunner:
    image: cp.icr.io/cp/cp4a/odm/odm-decisionrunner:8.12.0.1-amd64
    x-aws-pull_credentials: "arn:aws:secretsmanager:<aws_deployment_region>:<aws_account_id>:secret:IBMCPSecret-XXXXXX"
    x-ecs:
      EnableExecuteCommand: true     
    restart: always
    networks:
      - application
    labels:
      - productName=IBM Operational Decision Manager - Non Prod
      - productID=e32af5770e06427faae142993c691048
      - productVersion=8.12.0.1
      - productMetric=PROCESSOR_VALUE_UNIT
      - productChargedContainers=decisionrunner
    depends_on:
      odm-decisionserverconsole:
        condition: service_healthy
    environment:
      - RES_URL=http://test-odm-odm-decisioncenter-alb-540600390.eu-west-3.elb.amazonaws.com:81/res
      - HTTP_PORT=9081
      - DB_TYPE=postgres
      - DB_USER=<db_user>
      - DB_PASSWORD=<db_pwd>
      - DB_NAME=odmdb
      # Amazon RDS instance created for ODM. An example of the endpoint: odm-rds.XXXXXXX.eu-central-1.rds.amazonaws.com
      - DB_SERVER_NAME=<amazon_rds_endpoint>
    logging:
      driver: "awslogs"
    x-aws-policies:
      - arn:aws:iam::<aws_account_id>:policy/<policy_allow_access_S3_bucket>
    ports:
      - 9081
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '1'
          memory: 1G
      labels:
        ecs.task.family: odm
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "http://localhost:9081/DecisionRunner"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 50s

  odm-decisionserverruntime:
    image: cp.icr.io/cp/cp4a/odm/odm-decisionserverruntime:8.12.0.1-amd64
    x-aws-pull_credentials: "arn:aws:secretsmanager:<aws_deployment_region>:<aws_account_id>:secret:IBMCPSecret-XXXXXX"
    x-network:
      Ingress:
        Services:
          - Name: odm:odm-decisionserverconsole
    x-ecs:
      EnableExecuteCommand: true
    restart: always
    networks:
      - application
    environment:
      - DECISIONSERVERCONSOLE_NAME=odm-decisionserverconsole
      - HTTP_PORT=9082
      - DB_TYPE=postgres
      - DB_USER=<db_user>
      - DB_PASSWORD=<db_pwd>
      - DB_NAME=odmdb
      # Amazon RDS instance created for ODM. An example of the endpoint: odm-rds.XXXXXXX.eu-central-1.rds.amazonaws.com
      - DB_SERVER_NAME=<amazon_rds_endpoint>
    labels:
      - productName=IBM Operational Decision Manager
      - productID=b1a07d4dc0364452aa6206bb6584061d
      - productVersion=8.12.0.1
      - productMetric=PROCESSOR_VALUE_UNIT
      - productChargedContainers=decisionserverruntime 
    logging:
      driver: "awslogs"
    x-aws-policies:
      - arn:aws:iam::<aws_account_id>:policy/<policy_allow_access_S3_bucket>
    depends_on:
      odm-decisionserverconsole:
        condition: service_healthy
    ports:
      - 9082
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '1'
          memory: 1G
      labels:
        ecs.task.family: odm
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "http://localhost:9082/DecisionService"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 50s

  # IBM License Service - https://www.ibm.com/docs/en/was-liberty/base?topic=container-tracking-liberty-license-use-aws-ecs-fargate
  ibm-license-usage-logger-for-fargate:
    image: quay.io/opencloudio/ibm-license-usage-logger-for-fargate:latest
    x-ecs:
      EnableExecuteCommand: true     
    restart: always
    networks:
      - application
    labels:
      - productID=33687f02f10b4475aa7236f4cd2f94e6
      - productMetric=FREE
      - productName="IBM License Usage Logger for Fargate"
    environment:
      - AWS_S3_BUCKET_NAME=ibm-license-service-<aws_account_id>
      - AWS_S3_HTTPS_ENABLED=true
    logging:
      driver: "awslogs"
    x-aws-policies:
      - arn:aws:iam::<aws_account_id>:policy/<policy_allow_access_S3_bucket>
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 512M
      labels:
        ecs.task.family: odm
    healthcheck:
      test: ["CMD-SHELL", "./check-health.sh || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 300s