apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - all.yaml
patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/affinity/nodeAffinity/requiredDuringSchedulingIgnoredDuringExecution/nodeSelectorTerms/0/matchExpressions/-
        value:
          key: <customization.dedicatedNodeLabel>
          operator: "Exists"
    target:
      version: v1
      kind: Deployment
      name: ".*-odm-decisionserverconsole"
