OPENID_SERVER_URL=PING_FEDERATE_SERVER_URL
OPENID_PROVIDER=ping-federate
OPENID_GRANT_TYPE=client_credentials
OPENID_AUTHORIZATION_URL=PING_FEDERATE_SERVER_URL/authorize
OPENID_TOKEN_URL=PING_FEDERATE_SERVER_URL/token
OPENID_INTROSPECTION_URL=PING_FEDERATE_SERVER_URL/introspect
OPENID_SCOPE=odm_cc
OPENID_CLIENT_ID=PING_FEDERATE_CLIENT_ID
OPENID_CLIENT_SECRET=PING_FEDERATE_CLIENT_SECRET
OPENID_LOGOUT_URL=PING_FEDERATE_SERVER_URL/signoff
OPENID_LOGOUT_TOKEN_PARAM=id_token_hint
OPENID_ALLOWED_DOMAINS=apps.pingone.eu