apiVersion: operator.ibm.com/v1alpha1
kind: IBMLicensing
metadata:
  name: instance
spec:
  apiSecretToken: ibm-licensing-token
  datasource: datacollector
  httpsEnable: false
  ingressEnabled: true
  ingressOptions:
    annotations:
      ingress.kubernetes.io/rewrite-target: /
    path: /ibm-licensing-service-instance/*
  instanceNamespace: ibm-licensing
  license:
    accept: true
